### ISSUE TITLE
Tests look for files in `/Volumes/RHINO/...`

### ISSUE THREAD

**Issue by mivade** [pennmem/ram_utils#107]
Without specifying any markers to skip, I get failures/errors because of `/Volumes/RHINO` prepended to paths:

- `ramutils/test/test_powers.py::test_regression_compute_normalized_powers[R1350D_task_events_rhino.npy-R1350D_normalized_powers.npy-FRParameters]`
- `ramutils/test/test_powers.py::test_regression_compute_normalized_powers[R1354E_task_events_rhino.npy-R1354E_normalized_powers.npy-FRParameters]`
- `ramutils/test/test_powers.py::test_compute_powers[R1350D_task_events_rhino.npy]`
- `ramutils/test/test_powers.py::test_compute_powers[R1348J_task_events_rhino.npy]`
- `ramutils/test/test_powers.py::test_compute_single_session_powers`
- `ramutils/test/reports/test_summary.py::TestPSSessionSummary::()::test_location_summary::setup`
- `ramutils/test/reports/test_summary.py::TestPSSessionSummary::()::test_decision::setup`
- `ramutils/test/reports/test_summary.py::TestPSSessionSummary::()::test_to_dataframe::setup`

**Comment by zduey** [comment]
#116

**Comment by zduey** [comment]
Closing this because a PR has been merged that addresses the issue
