### ISSUE TITLE
Aggregated report vs. normal report

### ISSUE THREAD

**Issue by leondavis1** [pennmem/ram_utils#162]
What is the difference between these two types of report? When should I be looking at one vs the other?

**Comment by zduey** [comment]
Aggregated reports are specific to stim experiments and should be used to combine multiple stim sessions into a single report. It assumes/requires that all of the individual sessions have been processed and will not attempt to process a session that does not already have the summary objects built and saved. The other pipeline make_report is for constructing multi-session record-only reports and single-session stim reports. A single session record-only report is also possible, but that is a less common use case.

**Comment by zduey** [comment]
@leondavis1 should we keep this open, or is the above comment/in-person discussions sufficient? I can also leave it open and use it as a reminder to include some information differentiating the two in the ramutils documentation
