### ISSUE TITLE
Do not save experiment in retained_classifier container

### ISSUE THREAD

**Issue by zduey** [pennmem/ram_utils#191]
The retrained classifier is the same regardless of the stim experiment performed, so do not save the experiment name as part of the file. Otherwise, you end up with duplicated classifiers that you then have to ignore if doing multi-subject analyses

**Comment by mivade** [comment]
Does "retrained classifier" here mean something different than what it does in Ramulator? The post-saturation detection retrained classifier tends to differ from session to session...

**Comment by zduey** [comment]
"retrained" classifier in this case means something different. I refer to the classifier that is used/retrained in ramulator as the "actual" classifier. If the actual classifier cannot be found, then ramutils will do the training from scratch for the sake of the reports.

**Comment by zduey** [comment]
Fixed in #196
