### ISSUE TITLE
TICL experiment specs are incorrect

### ISSUE THREAD

**Issue by mivade** [pennmem/ram_utils#193]
The timings set in the `experiment_specs` section for TICL experiments are incorrect. Windows should be 525 ms each and we need some post-stim timings set (these are all supposed to be the same, but I'm trying to shoehorn this into what was going on in PS4).

Example:

```json
    "experiment_specs": {
      "biomarker_sample_start_time_offset": 0,
      "biomarker_sample_time_length": 525,
      "buffer_time": 524,
      "experiment_type": "TICL_FR",
      "freq_max": 180,
      "freq_min": 6,
      "num_items": 300,
      "num_freqs": 8,
      "post_stim_biomarker_sample_time_length": 525,
      "post_stim_buffer_time": 524,
      "post_stim_wait_time": 30,
      "stim_duration": 500,
      "version": "5.0.0"
    }
```

**Comment by zduey** [comment]
Is version 5.0.0 correct?

**Comment by mivade** [comment]
Version is a made up thing. We can call it whatever we want.

(It's 5.0.0 here because I originally copied from FR5.)

**Comment by mivade** [comment]
@zduey, can you also add `"refractory_duration": 0` to this? This will be additional post-stim delay which hopefully can be set to 0 in real experiments but we may need to increase it.
