### ISSUE TITLE
Refactor baseline recall event identification algorithm

### ISSUE THREAD

**Issue by zduey** [pennmem/ram_utils#204]
insert_baseline_retrieval_events is extremely confusing. Let's make it less confusing.

**Comment by zduey** [comment]
From @LoganJF 

The main issue here is, as Zach mentioned, that the code incorrectly sets the value for 'eegoffset' for any subject without a sample rate of 1000 in the function insert_baseline_retrieval_events. Attached below is a notebook with an updated version of the function that extracts the sample rate of the subject then will set the eegoffset using that information.

Additionally, I've included at the end my own personal code for creating matched events. It's much more verbose, but it's functional on RAM/scalp/pyFR data rather than just RAM data (and actually has comments).

https://gist.github.com/LoganJF/dcf040c570bab7a6eb288b991c2df079

**Comment by zduey** [comment]
@LoganJF -- I split the issue you submitted into two. The first one is the short term issue, which was to not assume a sample rate of 1000. That has been addressed in a current pull request. The other part of this is to refactor the algorithm. This could mean switching to using yours, but I'm hesitant to do that in the RAM "production" code since we have been using this other algorithm for all other sessions and so far as I am aware, there is only an issue with using it if you try to apply it to data that was not recorded with a 1000Hz sample rate.

**Comment by leondavis1** [comment]
Since we are now switching to use Logan's code, is this issue still relevant?

**Comment by zduey** [comment]
@leondavis1 -- Closing this issue since it is addressed by switching to Logan's code as part of #213
