### ISSUE TITLE
Bug in building joint reports

### ISSUE THREAD

**Issue by zduey** [pennmem/ram_utils#216]
ramutils version: 2.1.11

When building a joint report, sessions are left out if a report has already been built for that particular session. For example:

```shell
ram-report -s R1421M -x FR1 -j
```
should produce a joint report with at least one FR1 and one catFR1 session. However, it only produces a report with the FR1 session. The workaround is to use the `--rerun` flag, but that should not be necessary. There is likely a minor bug in the load_existing_results function that is not correctly looking for both FR and catFR sessions

**Comment by leondavis1** [comment]
So I'm sure I understand the bug, is this how you reproduce it:

- Build report with only catFR1 sessions
- Build joint FR1/catFR1 report 
- joint report will not include catFR1 sessions

**Comment by zduey** [comment]
@leondavis1 , the sequence would be just your first and last bullet point. If a single session record only report is built and then you try to build the joint report without adding "--rerun" it seems to ignore the catFR sessions.

**Comment by mivade** [comment]
Closing via #217.
