### ISSUE TITLE
Classifiers should not be recomputed when they can be deserialized

### ISSUE THREAD

**Issue by mivade** [pennmem/ram_utils#22]
Many reports recompute classifiers needlessly. According to @leondavis1, this originally happened because system 2 did not often have classifiers uploaded. In system 3, this always happens.

**Comment by mivade** [comment]
Marking this as a bug since the re-computed classifier is not always the same as what was actually used.

**Comment by maciekswat** [comment]
Ideally one would use  shared module to compute classifier and recomputation of classifier in the reporting code could be used as a "double-check" against what was generated in the experiment_config generation pipeline. Of course a test suite and proper provenance of classifier data would make this "double-check" reduntant

**Comment by zduey** [comment]
Thinking about this for ramutils 2.0, I think it would be good to have the option to recompute/retrain the classifier, but the default behavior should be to use the classifier that was active during the session

**Comment by zduey** [comment]
This is fully implemented/operational in the current ramutils code, so going to close this down.
